export const homeData = [
    {
        image: "/images/image 1.jpg",
        text: "Spicy seasoned seafood noodles",
        price: "$2.29",
        bowl: "20 Bowls",
        available: "120",
    },
    {
        image: "/images/image 5.jpg",
        text: "Salted Pasta with mushbroom sauce",
        price: "$2.69",
        bowl: "30 Bowls",
        available: "80",
    },
    {
        image: "/images/image 3.jpg",
        text: "Beef dumpling in hot and sour soup",
        price: "$3.49",
        bowl: " Bowls",
        available: "150",
    },
    {
        image: "/images/image 4.jpg",
        text: "Healthy noodle with spinach leaf",
        price: "$3.29",
        bowl: "22 Bowls",
        available: "90",
    },
    {
        image: "/images/image 4.jpg",
        text: "Hot spicy fried rice with omelet",
        price: "$3.49",
        bowl: "13 Bowls",
        available: "50",
    },
    {
        image: "/images/image 6.jpg",
        text: "spicy instant noodle with special omelette",
        price: "$3.59",
        bowl: "17 Bowls",
        available: "120",
    },
    {
        image: "/images/image 3.jpg",
        text: "Salted Pasta with mushbroom sauce",
        price: "$3.24",
        bowl: "9 Bowls",
        available: "230",
    },
    {
        image: "/images/image 6.jpg",
        text: "Spicy seasoned seafood noodles",
        price: "$2.98",
        bowl: "12 Bowls",
        available: "110",
    },
    {
        image: "/images/image 1.jpg",
        text: "Hot spicy fried rice with omelet",
        price: "$3.56",
        bowl: "23 Bowls",
        available: "70",
    },
];